### ISSUE TITLE
Support for MOL2 files

### ISSUE THREAD

**Issue by noahharrison64** [chemosim-lab/ProLIF#55] opened 2022-06-07 16:33 UTC
Hi,

I was wondering if there were any plans to enhance ProLIF with the ability to robustly read MOL2 files? I have a mol2 file that I am unable to read in, having tried all the methodologies suggested in the docs. Initially I was getting the following error
``RDKit ERROR: [17:50:37] non-ring atom 33 marked aromatic`` 
So tried using the Chem.MolFromMol2File workaround but to no avail - RDKit returns 'None' when trying to load this file. It seems this workaround fails due to RDKit struggling to read the file.

It seems to me my only workaround now is converting the MOL2 file into a PDB and reading in that. Would love to hear any other suggestions, or whether there are plans to implement a native MOL2 reader in future releases?

[MOL2 file saved as .txt for readability on drive ](https://drive.google.com/file/d/1W9poRQpwawXO2EGCWW2_grO38M4MymIT/view?usp=sharing)

Thanks,
Noah

**Comment by cbouy** [comment] 2022-06-07 20:09
Hi Noah, try this:

```python
prot = mda.Universe("prot.mol2")
# replace aromatic bonds with single bonds
for i, bo in enumerate(prot._topology.bonds.order):
    if bo == "ar":
        prot._topology.bonds.order[i] = 1
# clear the bond caching, just in case
prot._topology.bonds._cache.pop("bd", None)
# infer bond orders again
prot_mol = plf.Molecule.from_mda(prot.atoms)
```

It will remove all aromaticity, and then let the RDKitConverter in MDAnalysis infer bond orders again.

Some softwares produce MOL2 files where bonds which are not in a ring can still be marked as aromatic, which is incorrect. 
My opinion about this is that the problem is not parsers not being robust, the problem is this kind of MOL2 files having a very ~wrong~ unusual definition of what aromaticity is (likely to deal with conjugated bonds, but that's definitely not a good strategy to handle it, or at least that's my personal opinion about it).

So no, no plans to write my own MOL2 parser for this, especially since this workaround works (I'll add it to the documentation).

Hope that helps!
Cédric

**Comment by noahharrison64** [comment] 2022-06-08 08:49
Hi Cédric,

Totally agree, not a fan of MOL2. 

Tried this workaround and got it to work by adding the following line of code. Looks like I had to infer elements as well as bond orders.

`elements = mda.topology.guessers.guess_types(prot.atoms.names)
prot.add_TopologyAttr("elements", elements)`

Thanks for the help,
Noah

**Closed** 2022-06-08 23:16 UTC
Labels: documentation
