### ISSUE TITLE
Error related to vdwradii

### ISSUE THREAD

**Issue by kadiliissaar** [chemosim-lab/ProLIF#32] opened 2021-12-15 12:09 UTC
Thank you for creating this repository! I have trying to get a fingerprint for a protein-ligand complex from the PDB but am receiving the following error. Do you know why this may be?

**ValueError: vdw radii for types: O.2, C.ar, N.am, C.3, C.2, O.co2, O.3, P.3. These can be defined manually using the keyword 'vdwradii'**

This is the code I am using:
filename_protein = '1a1e_protein.pdb'
u = mda.Universe(filename_protein)
u.atoms.guess_bonds()
prot_sel = u.select_atoms("not resname LIG and not resname HOH and not resname DMS")
prot = plf.Molecule.from_mda(prot_sel, NoImplicit=False)

filename_ligand = '1a1e_ligand.mol2'
u = mda.Universe(filename_ligand)
u.atoms.guess_bonds()
lig_sel = u.select_atoms("not resname HOH")
lig = plf.Molecule.from_mda(lig_sel)

Files:
https://gist.github.com/kadiliissaar/a51ae9c48faf7e85449291982ba70c00
https://gist.github.com/kadiliissaar/90033b99f577ff90d69fc8be6a393fa7

**Comment by cbouy** [comment] 2021-12-16 20:38
Hi @kadiliissaar,

Thanks for providing the files and code snippet !
I managed to reproduce the error and identified what caused it in your ligand file.
I'll be a bit lengthy on the explanation as their are other issues hidden behind this one, so hopefully it will help other people to troubleshoot the problem more easily in the future. You can find the complete code snippet at the bottom.

```text
ValueError: vdw radii for types: O.2, C.ar, N.am, C.3, C.2, O.co2, O.3, P.3.
These can be defined manually using the keyword 'vdwradii'
```
This error happens when MDAnalysis tries to guess bonds based on the coordinates of each atom and their type. MDAnalysis typically deals with atom types from Gromacs, Charmm, or other MD software rather than Sybyl atom types (contained in `u.atoms.types` and displayed in the error message).
But because the MOL2 file already contains bond information, you can simply skip the `u.atoms.guess_bonds()` line, it's not needed here.
Now that this is out of the way, to convert the molecule from MDAnalysis to ProLIF/RDKit we need to add an `elements` attribute to the Universe as MOL2 files only contain Sybyl atom types and names:
```python
elements = mda.topology.guessers.guess_types(u.atoms.names)
u.add_TopologyAttr("elements", elements)
```
Now remains a final issue which is due to how different software handle conjugated bonds like those in a carboxylate group. The software that you used to generate the MOL2 file marks the carboxylate bonds as aromatic, although they aren't in a ring, and RDKit doesn't like that. A simple fix is to replace all aromatic bonds by single ones and let MDAnalysis infer the bond orders from there:
```python
u._topology.bonds.order = ["1" if bo == "ar" else bo for bo in u._topology.bonds.order]
```
And that's it for the ligand file!

For the protein, I notice that you are using `NoImplicit=False`. This will make MDAnalysis bypass the step where it's supposed to infer what bond order and formal charges should be assigned from the topology and valence of each atom. It's critical to leave this to `True` otherwise ProLIF won't be able to detect some of the interactions that rely on things like aromaticity for PiStacking.  
Now this brings it's own problem: some of the atoms in your protein are extremely close to each other, to the point where MDAnalysis incorrectly assumes that they are bonded. This is the case for two hydrogen atoms in SER225 and GLN228, and RDKit doesn't like hydrogen atoms with 2 bonds...  
The way to fix this is to tune the Van der Waals radius of hydrogen atoms that is used by MDAnalysis to guess which atoms are bonded to who.  
Using a radius of 0.98 instead of the default 1.1 solves the issue.
```python
u = mda.Universe(filename_protein, guess_bonds=True, vdwradii={"H": 0.98})
```

For reference, the table of vdw radii is in `mda.topology.core.tables.vdwradii`, and the code that I used to identify which atoms and bonds are problematic:
```python
print(prot_sel.bonds)
for atom in prot_sel:
    if atom.element == "H" and len(atom.bonds) > 1:
        print(atom, atom.bonds.indices)
```
```text
<TopologyGroup containing 3271 bonds>
<Atom 1262: HG of type H of resname SER, resid 225 and segid A and altLoc > [[1260 1261]
 [1261 1299]]
<Atom 1300: H of type H of resname GLN, resid 228 and segid A and altLoc > [[1261 1299]
 [1298 1299]]
<Atom 2243: HG1 of type H of resname THR, resid 183 and segid B and altLoc > [[2241 2242]
 [2242 2566]]
<Atom 2567: HZ2 of type H of resname LYS, resid 206 and segid B and altLoc > [[2242 2566]
 [2564 2566]]
```


### Complete fixed code:

```python
filename_protein = '1a1e_protein.pdb'
u = mda.Universe(filename_protein, guess_bonds=True, vdwradii={"H": 0.98})
prot_sel = u.select_atoms("not resname LIG and not resname HOH and not resname DMS")
prot = plf.Molecule.from_mda(prot_sel)

filename_ligand = '1a1e_ligand.mol2'
u = mda.Universe(filename_ligand)
elements = mda.topology.guessers.guess_types(u.atoms.names)
u.add_TopologyAttr("elements", elements)
u._topology.bonds.order = ["1" if bo == "ar" else bo for bo in u._topology.bonds.order]
lig_sel = u.select_atoms("not resname HOH")
lig = plf.Molecule.from_mda(lig_sel)

fp = plf.Fingerprint()
fp.run_from_iterable([lig], prot)
df = fp.to_dataframe()
df
```

PS: MDAnalysis seems to have merged all of the ligands residues that are inside the MOL2 file (ACE, PTR, GLU DIY) into a single one (ACE) as they all have the same residue number (1). You might want to manually change that in the file if you need to show the residue names even for the ligand.

Hope that helps,

Cédric

**Comment by kadiliissaar** [comment] 2021-12-22 09:58
This is very helpful explanation - thank you @cbouy!

**Closed** 2021-12-28 15:43 UTC
